---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Home
- type: directory
  path: content/en/home
  label: Home (En)
  create: all
  match: "**/*"
- type: directory
  path: content/ja/home
  label: Home (Ja)
  create: all
  match: "**/*"
- type: heading
  label: Get Involved
- type: directory
  path: content/en/get-involved
  label: Get Involved (En)
  create: all
  match: "**/*"
- type: directory
  path: content/ja/get-involved
  label: Get Involved (Ja)
  create: all
  match: "**/*"
- type: heading
  label: About
- type: directory
  path: content/en/about
  label: About (En)
  create: all
  match: "**/*"
- type: directory
  path: content/ja/about
  label: About (Ja)
  create: all
  match: "**/*"
- type: heading
  label: Other Pages
- type: directory
  path: content/en
  label: Pages (En)
  create: all
  match: "*"
- type: directory
  path: content/ja
  label: Pages (Ja)
  create: all
  match: "*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
